defmodule HardenLlmWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :harden_llm

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [
      check_origin: true,
      connect_info: [session: {HardenLlmWeb.SessionOptions, :options, []}]
    ],
    longpoll: [connect_info: [session: {HardenLlmWeb.SessionOptions, :options, []}]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :harden_llm,
    gzip: not code_reloading?,
    only: HardenLlmWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug PromEx.Plug, prom_ex_module: HardenLlmWeb.PromEx

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug HardenLlmWeb.SessionPlug
  plug HardenLlmWeb.Router
end
