ALTER TABLE user_sessions DROP CONSTRAINT user_sessions_owner_id_fkey;
ALTER TABLE llm_endpoint_credentials DROP CONSTRAINT llm_endpoint_credentials_owner_id_fkey;
ALTER TABLE llm_profiles DROP CONSTRAINT llm_profiles_owner_id_fkey;
ALTER TABLE llm_client_state DROP CONSTRAINT llm_client_state_owner_id_fkey;
ALTER TABLE llm_runs DROP CONSTRAINT llm_runs_owner_id_fkey;
ALTER TABLE llm_traces DROP CONSTRAINT llm_traces_owner_id_fkey;
ALTER TABLE llm_operation_cache DROP CONSTRAINT llm_operation_cache_owner_id_fkey;
ALTER TABLE llm_artifact_delete_batches DROP CONSTRAINT llm_artifact_delete_batches_owner_id_fkey;
ALTER TABLE llm_artifact_operations DROP CONSTRAINT llm_artifact_operations_owner_id_fkey;

DROP TABLE user_sessions;
DROP TABLE users RESTRICT;
