import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :harden_llm, HardenLlmWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :harden_llm, HardenLlmWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      hosts: ["localhost", "127.0.0.1"],
      # The Collector reaches this private-only route over the Compose network.
      # Caddy rejects /metrics before proxying any public request.
      paths: ["/metrics"]
    ]
  ]

# Do not print debug messages in production
config :logger, level: :info

config :logger, :default_handler,
  formatter:
    {LoggerJSON.Formatters.Basic,
     metadata: [
       :request_id,
       :trace_id,
       :span_id,
       :operation,
       :outcome,
       :status_class,
       :error_category
     ]}

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
