auth_enabled: true

server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3100
  grpc_listen_address: 0.0.0.0
  grpc_listen_port: 9096

common:
  path_prefix: /loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

storage_config:
  filesystem:
    directory: /loki/chunks
  aws:
    endpoint: garage:3900
    region: garage
    bucketnames: prls-loki
    access_key_id: ${PRLS_LOKI_S3_ACCESS_KEY}
    secret_access_key: ${PRLS_LOKI_S3_SECRET_KEY}
    s3forcepathstyle: true
    insecure: true

schema_config:
  configs:
    - from: "2024-01-01"
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h
    - from: "2026-08-23"
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: prls_index_
        period: 24h

limits_config:
  allow_structured_metadata: true
  volume_enabled: true
  retention_period: 2880h
  otlp_config:
    resource_attributes:
      attributes_config:
        - action: index_label
          attributes:
            - service.name
            - service.namespace
            - deployment.environment
            - prls.agent

compactor:
  working_directory: /loki/compactor
  retention_enabled: true
  delete_request_store: s3

analytics:
  reporting_enabled: false
